### ISSUE TITLE
re-configured an already configured device

### ISSUE THREAD

**Issue by ddewaele** [gerdmestdagh/embedded-device-connector#2]
Scenario : 
- Device has been configured to connect to the home wifi
- Device ends up in the office (different WIFI).

How can we get it to become connected again ?

2 possible ways : 
- When insert a usb stick containing a certain file, the application could detect this and put the device in AP mode again
- Some trigger (a gpio, or a timeout) could set the device in AP mode again after having booted without network connectivity.

**Comment by Mesger1** [comment]
if unable to connect to internet the device will startup accesspoint after 20seconds and every 5 minutes it will check to connect to the wifi with the last credentials
